### ISSUE TITLE
Exercise 1: Selectors

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#1]
https://github.com/OkwufuluezeD/jQuery/tree/master/exercise1/js/Selector.js

Selecting:
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Select all of the div elements that have a class of “module”.
Come up with three selectors that you could use to get the third item in the #myList unordered list. Which is the best to use? Why?
Select the label for the search input using an attribute selector.
Figure out how many elements on the page are hidden
Figure out how many image elements on the page have an alt attribute.
Select all of the odd table rows in the table body.

**Comment by osifoanosike** [comment]
There is a more efficient way to get the third `<li>`

**Comment by DOkwufulueze** [comment]
Correction implemented.
