### ISSUE TITLE
Exercise 10: Load content using JSON

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#10]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise10/js/Special.js

Open the file /exercises/index.html in your browser. Use the file /exercises/js/specials.js. Your task is to show the user details about the special for a given day when the user selects a day from the select dropdown.Append a target div after the form that's inside the #specials element; this will be where you put information about the special once you receive it.Bind to the change event of the select element; when the user changes the selection, send an Ajax request to /exercises/data/specials.json.
When the request returns a response, use the value the user selected in the select (hint: $.fn.val) to look up information about the special in the JSON response.
Add some HTML about the special to the target div you created.
Finally, because the form is now Ajax-enabled, remove the submit button from the form

**Comment by osifoanosike** [comment]
Do we need `_generateHTMLForSpecial` and `_doGenerateHTMLForSpecial`?

https://github.com/OkwufuluezeD/jQuery/blob/master/exercise10/js/Special.js#L31: You think we can optimize this with a ternary? ..see line 81 too.

**Comment by DOkwufulueze** [comment]
_generateHTMLForSpecial preferred.
Conditional statement optimization using ternary done.
