### ISSUE TITLE
Exercise 11: Product Grid Exercise ( with json data provided)

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#11]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise11/js/Product.js

Product Display.We have product data in csv format and images as followsGiven the csv file and images at this url - http://dl.dropbox.com/u/Here is the JSON for the same data.. http://dl.dropbox.com/Create a page which loads this json data and renders a store front. All the products should be displayed by default. Show a list of Brands in the left. Upon clicking the checkbox in front of a brand, only that particular brand products should be show, hide all others. If no checkbox is selected show products belonging to all brandsSimilarly have a filter for colorAlso create a toggle for All producs and available products - if user clicks “Available Products” show only products that are not sold out.The filters should work together - so I should be able to see Only Yellow products of Brand C which are Available

**Comment by osifoanosike** [comment]
- The Products should be displayed in a grid format..like we have on The Dealdey Site.
- Seems the extra js files still found their way in..??
- Pattern of element creation in constructor is not acceptable. 
- All CSS should be handled in style.css

**Comment by DOkwufulueze** [comment]
Products displayed in grid. 
Extra files removed. 
Element creation construction corrected. 
All css handled in style.css
