### ISSUE TITLE
Exercise 12: .delegate / .on() exercise

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#12]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise12/js/DivStack.js

Create a stack of divs. Initially an empty container should display- a button on right side says "add item", should add a div to the stack with an incremental number(starting from 1) - clicking any item in the stack should highlight that item- clicking the last item on the stack should remove that item from the stackhint: use jQuery delegate. live method has been removed from the latest version of jQuery so you may want to use on() or delegate()

**Comment by osifoanosike** [comment]
- Those extra js files ??
- Pattern of element creation in constructor is not acceptable.
- All CSS should be moved into style.css

**Comment by DOkwufulueze** [comment]
Extra files removed. 
Element creation construction corrected.
All css handled in style.css
