### ISSUE TITLE
Exercise2: Traversing

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#2]
https://github.com/OkwufuluezeD/jQuery/tree/master/exercise2/js/Traversal.js

Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Select all of the image elements on the page; log each image’s alt attribute.
Select the search input text box, then traverse up to the form and add a class to the form.
Select the list item inside #myList that has a class of “current” and remove that class from it; add a class of “current” to the next list item.
Select the select element inside #specials; traverse your way to the submit button.
Select the first list item in the #slideshow element; add the class “current” to it, and then add a class of “disabled” to its sibling elements.

**Comment by osifoanosike** [comment]
- Why do we have Selector.js here
- You shouldn't pass class properties as arguments to methods
- You should do your DOM selections
  outside your class.

**Comment by DOkwufulueze** [comment]
I keep carrying over previous files to newer works. That way, by the end, the web page looks different from how I got it with the combination of all jobs done on it.
But the file you need was pointed to in the URL I sent. The previous ones' job simply persisted across the page.

**Comment by osifoanosike** [comment]
I get you, but we need to go by the instructions.

**Comment by DOkwufulueze** [comment]
Corrections implemented.
