### ISSUE TITLE
Exercise 3: Manipulations

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#3]
https://github.com/OkwufuluezeD/jQuery/tree/master/exercise3/js/Manipulator.js

Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Add five new list items to the end of the unordered list #myList.
Remove the odd list items
Add another h2 and another paragraph to the last div.module
Add another option to the select element; give the option the value “Wednesday” 
Add a new div.module to the page after the last one; put a copy of one of the existing

**Comment by osifoanosike** [comment]
- Do not append strings, Append jQuery objects.
- Remove Irrelevant JS files. Replicate this correction for all exercises.
- DOM Selection should be done outside the class. Replicate this correction for all exercises.

**Comment by DOkwufulueze** [comment]
jQuery objects appended. 
Irrelevant js files removed.
DOM selection done outside the class.

**Comment by osifoanosike** [comment]
This doesn't seem to work.

**Comment by DOkwufulueze** [comment]
Please, what doesn't seem to work?
