### ISSUE TITLE
Exercise 4: Create an input hint

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#4]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise4/js/InputHint.js

Open the file /exercises/index.html in your browser. Use the file /exercises/js/inputHint.js or work in Firebug. Your task is to use the text of the label for the search input to create “hint” text for the search input. The steps are as follows:
Set the value of the search input to the text of the label element
Add a class of “hint” to the search input
Remove the label element
Bind a focus event to the search input that removes the hint text and the “hint” class
Bind a blur event to the search input that restores the hint text and “hint” class if no search text was entered

**Comment by osifoanosike** [comment]
- https://github.com/OkwufuluezeD/jQuery/blob/master/exercise4/js/InputHint.js#L25: There's a better way of doing this. See: http://api.jquery.com/bind/
- Does this code work? Please ensure it does.
- Do you need to separate: _performRemovalofHint & _removeHintText?

**Comment by DOkwufulueze** [comment]
.on used instead of .bind. 
_removeHintText now does the text removal itself. 
All codes are working.

**Comment by osifoanosike** [comment]
Your `if .. else` blocks can be optimized further

**Comment by DOkwufulueze** [comment]
if .. else blocks optimized
