### ISSUE TITLE
Exercise 6: Reveal hidden text

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#6]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise6/js/DisplayManager.js

Open the file /exercises/index.html in your browser. Use the file /exercises/js/blog.js. Your task is to add some interactivity to the blog section of the page. The spec for the feature is as follows:
Clicking on a headline in the #blog div should slide down the excerpt paragraph
Clicking on another headline should slide down its excerpt paragraph, and slide up any other currently showing excerpt paragraphs.

**Comment by osifoanosike** [comment]
_slideDownTargetExcerptAndSlideUpOthers: No better naming for this?

**Comment by DOkwufulueze** [comment]
_slideDownTargetExcerptAndSlideUpOthers is an attempt to make the method as descriptive as possible as you advised.

**Comment by osifoanosike** [comment]
how about toggleExcerpt ?

**Comment by DOkwufulueze** [comment]
toggleExcerpt used instead. Thanks a lot for the suggestion.
