### ISSUE TITLE
Exercise 8: Create a Slideshow

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery#8]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise8/js/Slideshow.js

This is a tough one if you do not know JS basics and particularly scopes.Open the file /exercises/index.html in your browser. Use the file /exercises/js/slideshow.js. Your task is to take a plain semantic HTML page and enhance it with JavaScript by adding a slideshow.
Move the #slideshow element to the top of the body.
Write code to cycle through the list items inside the element; fade one in, display it for a few seconds, then fade it out and fade in the next one.
When you get to the end of the list, start again at the beginning.
For an extra challenge, create a navigation area under the slideshow that shows how many images there are and which image you're currently viewing.

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/jQuery/blob/master/exercise8/js/Slideshow.js#L28. All CSS should be moved into style.css.

Clean code, i can't but commend.

**Comment by DOkwufulueze** [comment]
Thanks Osifo for the commendation.
All CSS now handled in style.css
